disabled_rules: # rule identifiers to exclude from running
  - identifier_name


excluded:
  - Pods

line_length: 400

nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10
